improve builds commands

diff --git a/client_mini/bin/build b/client_mini/bin/build
--- a/client_mini/bin/build
+++ b/client_mini/bin/build
@@ -1,15 +1,30 @@
 #!/bin/bash
 
-echo started
+step(){
+  echo ">>>>>>>-------------------------------------------------------------------------------------"
+  echo "-- Step: [ $1 ] >"
+  echo "-- Exec: [ $2 ] >"
+  `echo $2`
+  STEP_RESULT=$?
+  echo "<<<<<<<-------------------------------------------------------------------------------------"
 
-yarn
-echo installed
+  if [ "$STEP_RESULT" != "0" ]; then
+	echo "-- Step FAILED [ $1 ] with status $STEP_RESULT >"
+    exit 1
+  fi
 
-./bin/compile
-echo compiled
+  echo '+'
+  echo '+'
+}
 
-./bin/test
-echo tested
+echo "Build started"
 
-ruby ./bin/record_stats.rb
-echo recorded
+step "install libraries" "yarn"
+
+step "compile js" "./bin/compile"
+
+step "run tests" "./bin/test"
+
+step "record stats" "ruby ./bin/record_stats.rb"
+
+echo "Build OK"
